export const icons = {
    channelCreate: "https://i.imgur.com/zJmWj2V.png",
    channelDelete: "https://i.imgur.com/INVolf4.png",
    channelUpdate: "https://i.imgur.com/iFnJVf3.png",
    messageUpdate: "https://i.imgur.com/g1lUUj9.png",
    emojiCreate: "https://i.imgur.com/3l1btmt.png",
    emojiDelete: "https://i.imgur.com/W89Yctq.png",
    emojiUpdate: "https://i.imgur.com/FjcYnYF.png",
    memberRemove: "https://i.imgur.com/cLDGaDr.png",
    memberJoin: "https://i.imgur.com/krPmU7Q.png",
    botJoin: "https://i.imgur.com/4CUo5cE.png",
    botRemove: "https://i.imgur.com/b1EIYQ4.png",
    linkUpdate: "https://i.imgur.com/WDJ2i60.png",
    memberUpdate: "https://i.imgur.com/2ZdJwOl.png",
    guildUpdate: "https://i.imgur.com/VE9VdWR.png",
    linkCreate: "https://i.imgur.com/O7aN1KB.png",
    linkDelete: "https://i.imgur.com/Dq6vmFf.png",
    messageDelete: "https://i.imgur.com/2mkGs2Y.png",
    flagCreate: "https://i.imgur.com/w7xhLnO.png",
    flagDelete: "https://i.imgur.com/tOWjITM.png",
    flagUpdate: "https://i.imgur.com/qcRLUr4.png",
    connectCreate: "https://i.imgur.com/w2b2kVN.png",
    connectDelete: "https://i.imgur.com/9ZCrUBK.png",
    connectUpdate: "https://i.imgur.com/Cxx6btn.png",
};
